language: cpp
compiler: gcc
env:
  global:
  - APT_DEPENDENCIES="doxygen doxygen-latex libboost-all-dev boost1.48"
  - DEBSIGN_KEYID=5AE5CD75
notifications:
  email:
  - francois.keith@gmail.com
branches:
  only:
  - master
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install:
  - sudo add-apt-repository ppa:jkeiren/ppa/ubuntu
  - ./.travis/run  before_install
  - ./.travis/dependencies/eigen-3.2
